#!/bin/bash

echo "create a new virtual pc"

if [ $# -lt 1 ]
then
	echo "不告诉我虚拟机名字，我给你克隆到哪？"
	exit 2
fi

basedir=/home/mk/kvm_img

for vmname in $@
do
	
	if [ -f $basedir/$vmname.qcow2 ]
	then
		echo "大哥！有这个虚拟机的磁盘文件，我可不给你克隆！"
		exit 1
	fi
	vmxml=/tmp/$vmname.xml
	uuid=`uuidgen`
	let mac=$RANDOM%100
	if [ $mac -lt 10 ]
	then
		mac="0$mac"
	fi
	
	cp $basedir/base.xml $vmxml
	qemu-img create -f qcow2 -b $basedir/base.qcow2 $basedir/$vmname.qcow2 &> /dev/null
	sed -i "s/<uuid>.*</<uuid>$uuid</"  $vmxml
	sed -i "s/base/$vmname/g" $vmxml
	sed -i "s/e7/$mac/g" $vmxml
	virsh define $vmxml
	
	rm -rf $vmxml
done
